name: YAZZZZZZZ
favicon: null
layout_spectrum: 0.24654
typography_spectrum: 0.51677
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#d2d2d4'
    - '#3babb6'
    - '#939393'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0
purpose:
  - name: awareness
    item: null
    url: null
